# Generated by Django 5.1.1 on 2024-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.BigIntegerField()),
                ('homepage', models.URLField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=15, null=True)),
                ('original_language', models.CharField(max_length=5)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(max_length=255)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
